// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs0i014iMqHeS3hrn24lDoC20BdEMAu-M',
    appId: '1:734786795251:web:8e67f30aab9152d2df2986',
    messagingSenderId: '734786795251',
    projectId: 'chat-chat-314db',
    authDomain: 'chat-chat-314db.firebaseapp.com',
    storageBucket: 'chat-chat-314db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcpTLGtJNa1E1ZeDPQ-l5B2xD4UKph-zs',
    appId: '1:734786795251:android:8159a22cedf23ac4df2986',
    messagingSenderId: '734786795251',
    projectId: 'chat-chat-314db',
    storageBucket: 'chat-chat-314db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAmfFP5GtM4PKb-6_COjHkH4bOwHVC5ao',
    appId: '1:734786795251:ios:74c195b27b66cb2fdf2986',
    messagingSenderId: '734786795251',
    projectId: 'chat-chat-314db',
    storageBucket: 'chat-chat-314db.appspot.com',
    iosBundleId: 'com.example.chatChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAmfFP5GtM4PKb-6_COjHkH4bOwHVC5ao',
    appId: '1:734786795251:ios:c96d961e73d75086df2986',
    messagingSenderId: '734786795251',
    projectId: 'chat-chat-314db',
    storageBucket: 'chat-chat-314db.appspot.com',
    iosBundleId: 'com.example.chatChat.RunnerTests',
  );
}
